name: Action-Test

run-name: "Action-Test - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ActionTestBasic:
    name: Action-Test - [Basic]
    runs-on: ubuntu-latest
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      # Upload artifact from tests:
      - name: Upload artifact [PATH-Windows-TestResults]
        uses: actions/upload-artifact@v4
        with:
          name: PATH-Windows-TestResults
          path: ./tests/TestResults/PATH-Windows-TestResults
          retention-days: 1
      - name: Upload artifact [PSModuleLint-Module-Windows-TestResults]
        uses: actions/upload-artifact@v4
        with:
          name: PSModuleLint-Module-Windows-TestResults
          path: ./tests/TestResults/PSModuleLint-Module-Windows-TestResults
          retention-days: 1
      - name: Upload artifact [PSModuleLint-SourceCode-Windows-TestResults]
        uses: actions/upload-artifact@v4
        with:
          name: PSModuleLint-SourceCode-Windows-TestResults
          path: ./tests/TestResults/PSModuleLint-SourceCode-Windows-TestResults
          retention-days: 1
      - name: Upload artifact [PSModuleTest-Module-Windows-TestResults]
        uses: actions/upload-artifact@v4
        with:
          name: PSModuleTest-Module-Windows-TestResults
          path: ./tests/TestResults/PSModuleTest-Module-Windows-TestResults
          retention-days: 1
      - name: Upload artifact [PSModuleTest-SourceCode-Windows-TestResults]
        uses: actions/upload-artifact@v4
        with:
          name: PSModuleTest-SourceCode-Windows-TestResults
          path: ./tests/TestResults/PSModuleTest-SourceCode-Windows-TestResults
          retention-days: 1

      - name: Action-Test
        uses: ./
        with:
          SourceCodeTestSuites: '[{"OSName": "Windows"}'
          PSModuleTestSuites: '[{"OSName": "Windows"}]'
          ModuleTestSuites: '[{"TestName": "PATH", "OSName": "Windows"}]'
